"""empty message

Revision ID: 2eaf3866227b
Revises: bc9565e5279d
Create Date: 2023-06-26 17:11:15.790797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eaf3866227b'
down_revision = 'bc9565e5279d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('auth_string', sa.String(), nullable=True))
    op.drop_column('clients', 'hmac_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hmac_bytes', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'auth_string')
    # ### end Alembic commands ###
