"""empty message

Revision ID: 46b42f1c232b
Revises: 2eaf3866227b
Create Date: 2023-06-26 21:15:50.156861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b42f1c232b'
down_revision = '2eaf3866227b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sock_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'sock_number')
    # ### end Alembic commands ###
