"""empty message

Revision ID: 64e11dc67799
Revises: 
Create Date: 2023-06-01 11:33:28.237340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e11dc67799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_client_id_fkey', 'history', type_='foreignkey')
    op.drop_column('history', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('history_client_id_fkey', 'history', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
