"""empty message

Revision ID: a1293026adc9
Revises: 8740690d0703
Create Date: 2023-06-01 12:29:58.209149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1293026adc9'
down_revision = '8740690d0703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clients_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frend_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.id'], name='contacts_clients_id_fkey'),
    sa.ForeignKeyConstraint(['frend_id'], ['clients.id'], name='contacts_frend_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey')
    )
    # ### end Alembic commands ###
