"""empty message

Revision ID: bc9565e5279d
Revises: d8cc428c960b
Create Date: 2023-06-25 21:43:52.505285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9565e5279d'
down_revision = 'd8cc428c960b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
