"""empty message

Revision ID: d8cc428c960b
Revises: f93d950f6947
Create Date: 2023-06-25 19:01:55.730633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cc428c960b'
down_revision = 'f93d950f6947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hmac_bytes', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'hmac_bytes')
    # ### end Alembic commands ###
