"""empty message

Revision ID: f93d950f6947
Revises: fc84b901f5eb
Create Date: 2023-06-25 16:00:44.484361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d950f6947'
down_revision = 'fc84b901f5eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_authenticated')
    # ### end Alembic commands ###
