"""empty message

Revision ID: fa7b81d0c1b2
Revises: 64e11dc67799
Create Date: 2023-06-01 11:52:13.474684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7b81d0c1b2'
down_revision = '64e11dc67799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('registered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'registered_at')
    # ### end Alembic commands ###
