"""empty message

Revision ID: fc84b901f5eb
Revises: 
Create Date: 2023-06-15 20:48:24.063041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc84b901f5eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('status_online', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=True),
    sa.Column('owner_frend', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_frend'], ['clients.login'], ),
    sa.ForeignKeyConstraint(['owner_login'], ['clients.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=255), nullable=True),
    sa.Column('client_login', sa.String(length=255), nullable=True),
    sa.Column('client_message', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_login'], ['clients.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('contacts')
    op.drop_table('clients')
    # ### end Alembic commands ###
